import type { Question } from './types'

export const QUESTIONNAIRE_VERSION = 'v0.1'

const q = (
  id: string,
  axis: string,
  type: Question['type'],
  text: string,
  options: Question['options'] = [],
  required = true,
  module: 'person' | 'brand' = 'person',
  archetype?: string,
): Omit<Question, 'order' | 'version'> => ({
  id,
  axis,
  type,
  text,
  options,
  required,
  module,
  archetype,
})

const LIKERT: Question['type'] = 'likert'

export const questionBank: Omit<Question, 'order' | 'version'>[] = [
  // ── EIXO IDENTIDADE ────────────────────────────────────────────────
  q('id_01', 'identity', LIKERT, 'Costumo agir de acordo com aquilo em que acredito, mesmo quando minha opinião difere da maioria.', [], true, 'person', 'rebel'),
  q('id_02', 'identity', LIKERT, 'Tenho clareza sobre quem sou e sobre o que é realmente importante para mim.', [], true, 'person', 'sage'),
  q('id_03', 'identity', LIKERT, 'Quando penso em mim, reconheço minhas qualidades com a mesma facilidade com que reconheço meus limites.', [], true, 'person', 'innocent'),
  q('id_04', 'identity', LIKERT, 'Busco constantemente novas experiências, lugares e aprendizados.', [], true, 'person', 'explorer'),
  q('id_05', 'identity', LIKERT, 'Tenho facilidade para criar ideias novas e diferentes do que já existe.', [], true, 'person', 'creator'),
  q('id_06', 'identity', LIKERT, 'Assumo naturalmente posições de condução quando percebo que algo precisa ser organizado.', [], true, 'person', 'ruler'),
  q('id_07', 'identity', LIKERT, 'Minha identidade está fortemente ligada ao cuidado com as pessoas próximas a mim.', [], true, 'person', 'caregiver'),
  q('id_08', 'identity', LIKERT, 'Sinto que existem partes de mim que ainda não conheço bem e que gostaria de compreender.', [], true, 'person', 'magician'),
  q('id_09', 'identity', LIKERT, 'Costumo levar a vida com leveza, sem me levar tão a sério.', [], true, 'person', 'jester'),
  q('id_10', 'identity', LIKERT, 'Sinto que me expresso melhor quando estou em conexão com outras pessoas.', [], true, 'person', 'lover'),

  // ── EIXO RELACIONAMENTOS ───────────────────────────────────────────
  q('rl_01', 'relationships', LIKERT, 'Tenho facilidade para estabelecer vínculos de confiança com novas pessoas.', [], true, 'person', 'lover'),
  q('rl_02', 'relationships', LIKERT, 'Em um grupo, percebo com sensibilidade as necessidades das pessoas ao meu redor.', [], true, 'person', 'caregiver'),
  q('rl_03', 'relationships', LIKERT, 'Prefiro realizar trabalhos em colaboração do que de forma totalmente isolada.', [], true, 'person', 'orphan'),
  q('rl_04', 'relationships', LIKERT, 'Sinto-me seguro quando sei que faço parte de um grupo.', [], true, 'person', 'orphan'),
  q('rl_05', 'relationships', LIKERT, 'Tenho facilidade para expressar o que sinto pelas pessoas.', [], true, 'person', 'lover'),
  q('rl_06', 'relationships', LIKERT, 'Respeito os limites dos outros e defendo os meus quando necessário.', [], true, 'person', 'warrior'),
  q('rl_07', 'relationships', LIKERT, 'Quando alguém depende de mim, sinto responsabilidade genuína em ajudar.', [], true, 'person', 'caregiver'),
  q('rl_08', 'relationships', LIKERT, 'Prefiro poucas relações profundas a muitas relações superficiais.', [], true, 'person', 'explorer'),
  q('rl_09', 'relationships', LIKERT, 'Diante de um conflito, procuro compreender o outro lado antes de reagir.', [], true, 'person', 'sage'),

  // ── EIXO LIDERANÇA E AUTONOMIA ─────────────────────────────────────
  q('ld_01', 'leadership', LIKERT, 'Quando uma decisão precisa ser tomada, assumo a responsabilidade com naturalidade.', [], true, 'person', 'ruler'),
  q('ld_02', 'leadership', LIKERT, 'Costumo tomar iniciativa mesmo sem esperar que alguém me autorize.', [], true, 'person', 'warrior'),
  q('ld_03', 'leadership', LIKERT, 'Sou disciplinado para cumprir aquilo que me proponho.', [], true, 'person', 'warrior'),
  q('ld_04', 'leadership', LIKERT, 'Tenho facilidade para inspirar e mobilizar outras pessoas.', [], true, 'person', 'ruler'),
  q('ld_05', 'leadership', LIKERT, 'Prefiro conduzir processos a apenas acompanhar o que acontece.', [], true, 'person', 'ruler'),
  q('ld_06', 'leadership', LIKERT, 'Mantenho o foco em meus objetivos mesmo diante de obstáculos.', [], true, 'person', 'warrior'),
  q('ld_07', 'leadership', LIKERT, 'Confio na minha capacidade de decidir por conta própria.', [], true, 'person', 'explorer'),
  q('ld_08', 'leadership', LIKERT, 'Assumir autoridade me faz sentir confortável e natural.', [], true, 'person', 'ruler'),
  q('ld_09', 'leadership', LIKERT, 'Quando lidero, busco extrair o melhor de cada pessoa da equipe.', [], true, 'person', 'sage'),

  // ── EIXO PROPÓSITO ─────────────────────────────────────────────────
  q('pp_01', 'purpose', LIKERT, 'Tenho um sentido claro que orienta as decisões importantes da minha vida.', [], true, 'person', 'magician'),
  q('pp_02', 'purpose', LIKERT, 'Sinto que nasci para contribuir de uma forma específica com as pessoas.', [], true, 'person', 'magician'),
  q('pp_03', 'purpose', LIKERT, 'Sonho em deixar uma marca que permaneça depois de mim.', [], true, 'person', 'creator'),
  q('pp_04', 'purpose', LIKERT, 'Minhas ações do dia a dia estão alinhadas com aquilo que considero importante.', [], true, 'person', 'sage'),
  q('pp_05', 'purpose', LIKERT, 'Tenho uma visão clara do futuro que quero construir para mim.', [], true, 'person', 'explorer'),
  q('pp_06', 'purpose', LIKERT, 'O que mais me motiva é gerar impacto real na vida das pessoas.', [], true, 'person', 'caregiver'),
  q('pp_07', 'purpose', LIKERT, 'Mesmo diante de dificuldades, encontro sentido naquilo que faço.', [], true, 'person', 'warrior'),

  // ── EIXO ATUAÇÃO E CARREIRA ────────────────────────────────────────
  q('cr_01', 'career', LIKERT, 'Prefiro ambientes de trabalho que me permitam autonomia e flexibilidade.', [], true, 'person', 'explorer'),
  q('cr_02', 'career', LIKERT, 'Tenho talento natural para organizar processos, prazos e rotinas.', [], true, 'person', 'ruler'),
  q('cr_03', 'career', LIKERT, 'Costumo me destacar em atividades que exigem criatividade.', [], true, 'person', 'creator'),
  q('cr_04', 'career', LIKERT, 'Quando surge um problema, busco soluções práticas e objetivas.', [], true, 'person', 'warrior'),
  q('cr_05', 'career', LIKERT, 'Gosto de variar as atividades e evitar rotinas repetitivas.', [], true, 'person', 'explorer'),
  q('cr_06', 'career', LIKERT, 'Tenho facilidade para transformar ideias em ações concretas.', [], true, 'person', 'warrior'),
  q('cr_07', 'career', LIKERT, 'Sinto-me realizado quando construo algo do zero.', [], true, 'person', 'creator'),
  q('cr_08', 'career', LIKERT, 'Consigo manter o foco em tarefas longas e complexas.', [], true, 'person', 'ruler'),

  // ── EIXO COMUNICAÇÃO ───────────────────────────────────────────────
  q('cm_01', 'communication', LIKERT, 'Consigo expressar minhas ideias com clareza.', [], true, 'person', 'sage'),
  q('cm_02', 'communication', LIKERT, 'Sou persuasivo quando preciso defender um ponto de vista.', [], true, 'person', 'warrior'),
  q('cm_03', 'communication', LIKERT, 'Tenho facilidade para falar diante de grupos de pessoas.', [], true, 'person', 'ruler'),
  q('cm_04', 'communication', LIKERT, 'Quando converso, presto atenção real no que o outro está dizendo.', [], true, 'person', 'caregiver'),
  q('cm_05', 'communication', LIKERT, 'Costumo ser direto e transparente em minha comunicação.', [], true, 'person', 'warrior'),
  q('cm_06', 'communication', LIKERT, 'Uso o bom humor para tornar as conversas mais leves.', [], true, 'person', 'jester'),

  // ── EIXO DESAFIOS ──────────────────────────────────────────────────
  q('dc_01', 'challenges', LIKERT, 'Em situações de pressão, mantenho clareza para decidir.', [], true, 'person', 'warrior'),
  q('dc_02', 'challenges', LIKERT, 'Quando algo muda de repente, adapto-me com rapidez.', [], true, 'person', 'explorer'),
  q('dc_03', 'challenges', LIKERT, 'Quando algo não sai como planejei, é difícil para mim manter a calma.', [], true, 'person', 'shadow'),
  q('dc_04', 'challenges', LIKERT, 'Diante de um fracasso, consigo recomeçar sem desanimar.', [], true, 'person', 'warrior'),
  q('dc_05', 'challenges', LIKERT, 'Costumo evitar situações em que posso parecer incapaz.', [], true, 'person', 'shadow'),
  q('dc_06', 'challenges', LIKERT, 'Preciso da aprovação dos outros para me sentir seguro nas minhas escolhas.', [], true, 'person', 'shadow'),
  q('dc_07', 'challenges', LIKERT, 'Quando estou sobrecarregado, insisto em resolver sozinho em vez de pedir ajuda.', [], true, 'person', 'shadow'),
  q('dc_08', 'challenges', LIKERT, 'Comparo-me com outras pessoas com mais frequência do que gostaria.', [], true, 'person', 'shadow'),
  q('dc_09', 'challenges', LIKERT, 'Quando recebo críticas, costumo levá-las para o lado pessoal.', [], true, 'person', 'shadow'),

  // ── EIXO POTENCIALIDADES ───────────────────────────────────────────
  q('pt_01', 'potential', LIKERT, 'Sinto que tenho capacidades que ainda não uso plenamente.', [], true, 'person', 'magician'),
  q('pt_02', 'potential', LIKERT, 'Aprendo coisas novas com facilidade e rapidez.', [], true, 'person', 'explorer'),
  q('pt_03', 'potential', LIKERT, 'Quando quero, consigo mobilizar pessoas em torno de uma causa.', [], true, 'person', 'ruler'),
  q('pt_04', 'potential', LIKERT, 'Costumo enxergar soluções que outras pessoas não percebem.', [], true, 'person', 'magician'),
  q('pt_05', 'potential', LIKERT, 'Minha intuição costuma me orientar bem nas escolhas.', [], true, 'person', 'magician'),
  q('pt_06', 'potential', LIKERT, 'Consigo transformar dificuldades em oportunidades.', [], true, 'person', 'creator'),
  q('pt_07', 'potential', LIKERT, 'Sou capaz de improvisar quando não tenho todas as respostas.', [], true, 'person', 'jester'),

  // ── EIXO DESENVOLVIMENTO ───────────────────────────────────────────
  q('dv_01', 'development', LIKERT, 'Reconheço minhas contradições internas e entendo que elas fazem parte de quem sou.', [], true, 'person', 'sage'),
  q('dv_02', 'development', LIKERT, 'Procuro compreender por que reajo de determinadas formas.', [], true, 'person', 'sage'),
  q('dv_03', 'development', LIKERT, 'Assumo responsabilidade pelas escolhas que fiz até aqui.', [], true, 'person', 'warrior'),
  q('dv_04', 'development', LIKERT, 'Tenho consciência dos meus padrões de comportamento e de suas repetições.', [], true, 'person', 'sage'),
  q('dv_05', 'development', LIKERT, 'Estou aberto a transformar aspectos de mim que já não me servem.', [], true, 'person', 'magician'),
  q('dv_06', 'development', LIKERT, 'Consigo integrar minhas dimensões pessoal e profissional em uma vida coerente.', [], true, 'person', 'ruler'),
  q('dv_07', 'development', LIKERT, 'Meu comportamento em público reflete bem quem eu sou por dentro.', [], true, 'person', 'innocent'),
  q('dv_08', 'development', LIKERT, 'Sinto que estou vivendo um momento importante de transformação.', [], true, 'person', 'magician'),

  // ── PERGUNTAS ABERTAS ──────────────────────────────────────────────
  q('op_01', 'open', 'open', 'Quais são seus maiores sonhos e aspirações?'),
  q('op_02', 'open', 'open', 'O que motiva você a levantar todos os dias?'),
  q('op_03', 'open', 'open', 'Qual é o principal objetivo que deseja alcançar nesta fase da sua vida?'),
  q('op_04', 'open', 'open', 'Como gostaria de ser lembrado?'),
  q('op_05', 'open', 'open', 'O que você acredita que faz melhor do que a maioria das pessoas?'),
  q('op_06', 'open', 'open', 'O que gostaria de desenvolver em si?'),
  q('op_07', 'open', 'open', 'Qual é hoje o maior desafio que enfrenta?'),
  q('op_08', 'open', 'open', 'Que tipo de contribuição gostaria de oferecer às pessoas?'),
  q('op_09', 'open', 'open', 'Descreva, em poucas palavras, o momento de vida que você vive hoje.'),

  // ── MARCA / ORGANIZAÇÃO ────────────────────────────────────────────
  q(
    'br_01',
    'brand',
    'single',
    'A afirmação que mais se aproxima da essência desta marca ou projeto é:',
    [
      { id: 'b1', label: 'Oferece segurança e acolhimento, como um abrigo.' },
      { id: 'b2', label: 'Questiona padrões e propõe novos caminhos.' },
      { id: 'b3', label: 'Oferece conhecimento, clareza e profundidade.' },
      { id: 'b4', label: 'Convida à liberdade, à descoberta e à aventura.' },
      { id: 'b5', label: 'Cria, inova e transforma ideias em realidades.' },
      { id: 'b6', label: 'Lidera, organiza e inspira confiança.' },
      { id: 'b7', label: 'Transmite simplicidade, pureza e esperança.' },
      { id: 'b8', label: 'Conecta pessoas e gera afeto.' },
      { id: 'b9', label: 'Transforma vidas e desperta visão.' },
      { id: 'b10', label: 'É forte, determinada e disciplinada.' },
      { id: 'b11', label: 'Acolhe a realidade como ela é, com verdade.' },
      { id: 'b12', label: 'Traz leveza, humor e espontaneidade.' },
    ],
    true,
    'brand',
    'essence',
  ),
  q(
    'br_02',
    'brand',
    'multiple',
    'O que você deseja que as pessoas percebam imediatamente nesta marca ou projeto?',
    [
      { id: 'p1', label: 'Credibilidade' },
      { id: 'p2', label: 'Acolhimento' },
      { id: 'p3', label: 'Inovação' },
      { id: 'p4', label: 'Qualidade' },
      { id: 'p5', label: 'Leveza' },
      { id: 'p6', label: 'Força' },
      { id: 'p7', label: 'Propósito' },
      { id: 'p8', label: 'Conexão' },
    ],
    true,
    'brand',
    'positioning',
  ),
  q(
    'br_03',
    'brand',
    'multiple',
    'Esta marca busca oferecer principalmente:',
    [
      { id: 'o1', label: 'Segurança' },
      { id: 'o2', label: 'Transformação' },
      { id: 'o3', label: 'Conhecimento' },
      { id: 'o4', label: 'Experiências' },
      { id: 'o5', label: 'Soluções criativas' },
      { id: 'o6', label: 'Organização' },
      { id: 'o7', label: 'Esperança' },
      { id: 'o8', label: 'Cuidado' },
      { id: 'o9', label: 'Visão' },
      { id: 'o10', label: 'Resultados' },
      { id: 'o11', label: 'Verdade' },
      { id: 'o12', label: 'Leveza' },
    ],
    true,
    'brand',
    'positioning',
  ),
  q(
    'br_04',
    'brand',
    'multiple',
    'Esta marca ajuda as pessoas a:',
    [
      { id: 'a1', label: 'Sentirem-se protegidas' },
      { id: 'a2', label: 'Rompem padrões' },
      { id: 'a3', label: 'Compreenderem melhor o mundo' },
      { id: 'a4', label: 'Descobrirem novos caminhos' },
      { id: 'a5', label: 'Criarem e realizarem' },
      { id: 'a6', label: 'Liderarem com confiança' },
      { id: 'a7', label: 'Confiar novamente' },
      { id: 'a8', label: 'Conectarem-se com mais profundidade' },
      { id: 'a9', label: 'Transformarem suas vidas' },
      { id: 'a10', label: 'Superarem desafios' },
      { id: 'a11', label: 'Serem mais verdadeiras' },
      { id: 'a12', label: 'Viverem com mais leveza' },
    ],
    true,
    'brand',
    'positioning',
  ),
  q(
    'br_05',
    'brand',
    'multiple',
    'Como você gostaria que as pessoas descrevessem esta marca?',
    [
      { id: 'd1', label: 'Confiável' },
      { id: 'd2', label: 'Humana' },
      { id: 'd3', label: 'Inovadora' },
      { id: 'd4', label: 'Sofisticada' },
      { id: 'd5', label: 'Acolhedora' },
      { id: 'd6', label: 'Determinada' },
      { id: 'd7', label: 'Inspiradora' },
      { id: 'd8', label: 'Autêntica' },
    ],
    true,
    'brand',
    'perception',
  ),
  q(
    'br_06',
    'brand',
    'multiple',
    'O propósito desta marca está principalmente relacionado a:',
    [
      { id: 'r1', label: 'Proteger e cuidar' },
      { id: 'r2', label: 'Provocar mudanças' },
      { id: 'r3', label: 'Compartilhar conhecimento' },
      { id: 'r4', label: 'Expandir horizontes' },
      { id: 'r5', label: 'Criar o novo' },
      { id: 'r6', label: 'Conduzir e organizar' },
      { id: 'r7', label: 'Transmitir esperança' },
      { id: 'r8', label: 'Gerar conexões' },
      { id: 'r9', label: 'Transformar vidas' },
      { id: 'r10', label: 'Gerar impacto' },
      { id: 'r11', label: 'Ser verdadeira' },
      { id: 'r12', label: 'Levar alegria' },
    ],
    true,
    'brand',
    'purpose',
  ),
  q(
    'br_07',
    'brand',
    'multiple',
    'Quais características você gostaria que estivessem presentes na percepção desta marca?',
    [
      { id: 'c1', label: 'Criatividade' },
      { id: 'c2', label: 'Confiança' },
      { id: 'c3', label: 'Organização' },
      { id: 'c4', label: 'Liberdade' },
      { id: 'c5', label: 'Autoridade' },
      { id: 'c6', label: 'Cuidado' },
      { id: 'c7', label: 'Inovação' },
      { id: 'c8', label: 'Simplicidade' },
      { id: 'c9', label: 'Fortalecimento' },
      { id: 'c10', label: 'Propósito' },
    ],
    true,
    'brand',
    'perception',
  ),
  q('br_08', 'brand', 'text', 'Qual é a principal promessa que esta marca faz?', [], true, 'brand', 'essence'),
  q('br_09', 'brand', 'text', 'Como esta marca se diferencia das demais?', [], true, 'brand', 'positioning'),
]

export const LIKERT_SCALE: { value: number; label: string }[] = [
  { value: 1, label: 'Discordo totalmente' },
  { value: 2, label: 'Discordo' },
  { value: 3, label: 'Nem discordo, nem concordo' },
  { value: 4, label: 'Concordo' },
  { value: 5, label: 'Concordo totalmente' },
]

const buildQuestions = (module: 'person' | 'brand'): Question[] => {
  const list = questionBank.filter((item) => item.module === module)
  return list.map((item, index) => ({
    ...item,
    version: QUESTIONNAIRE_VERSION,
    order: index + 1,
  }))
}

export const personQuestions = (): Question[] => buildQuestions('person')
export const brandQuestions = (): Question[] => buildQuestions('brand')
