-- ============================================================
-- SynaptEssence360® — Seed do banco de perguntas v0.1
-- Gerado por scripts/generate-seed.mjs
-- ============================================================

insert into public.questionnaire_versions (code, name, active) values
  ('v0.1', 'SynaptEssence360® — Levantamento v0.1', true)
on conflict (code) do nothing;

insert into public.questions
  (qid, version, axis, ord, type, text, options, required, module, archetype)
values
  ('id_01', 'v0.1', 'identity', 1, 'likert', 'Costumo agir de acordo com aquilo em que acredito, mesmo quando minha opinião difere da maioria.', '[]'::jsonb, true, 'person', 'rebel'),
  ('id_02', 'v0.1', 'identity', 2, 'likert', 'Tenho clareza sobre quem sou e sobre o que é realmente importante para mim.', '[]'::jsonb, true, 'person', 'sage'),
  ('id_03', 'v0.1', 'identity', 3, 'likert', 'Quando penso em mim, reconheço minhas qualidades com a mesma facilidade com que reconheço meus limites.', '[]'::jsonb, true, 'person', 'innocent'),
  ('id_04', 'v0.1', 'identity', 4, 'likert', 'Busco constantemente novas experiências, lugares e aprendizados.', '[]'::jsonb, true, 'person', 'explorer'),
  ('id_05', 'v0.1', 'identity', 5, 'likert', 'Tenho facilidade para criar ideias novas e diferentes do que já existe.', '[]'::jsonb, true, 'person', 'creator'),
  ('id_06', 'v0.1', 'identity', 6, 'likert', 'Assumo naturalmente posições de condução quando percebo que algo precisa ser organizado.', '[]'::jsonb, true, 'person', 'ruler'),
  ('id_07', 'v0.1', 'identity', 7, 'likert', 'Minha identidade está fortemente ligada ao cuidado com as pessoas próximas a mim.', '[]'::jsonb, true, 'person', 'caregiver'),
  ('id_08', 'v0.1', 'identity', 8, 'likert', 'Sinto que existem partes de mim que ainda não conheço bem e que gostaria de compreender.', '[]'::jsonb, true, 'person', 'magician'),
  ('id_09', 'v0.1', 'identity', 9, 'likert', 'Costumo levar a vida com leveza, sem me levar tão a sério.', '[]'::jsonb, true, 'person', 'jester'),
  ('id_10', 'v0.1', 'identity', 10, 'likert', 'Sinto que me expresso melhor quando estou em conexão com outras pessoas.', '[]'::jsonb, true, 'person', 'lover'),
  ('rl_01', 'v0.1', 'relationships', 11, 'likert', 'Tenho facilidade para estabelecer vínculos de confiança com novas pessoas.', '[]'::jsonb, true, 'person', 'lover'),
  ('rl_02', 'v0.1', 'relationships', 12, 'likert', 'Em um grupo, percebo com sensibilidade as necessidades das pessoas ao meu redor.', '[]'::jsonb, true, 'person', 'caregiver'),
  ('rl_03', 'v0.1', 'relationships', 13, 'likert', 'Prefiro realizar trabalhos em colaboração do que de forma totalmente isolada.', '[]'::jsonb, true, 'person', 'orphan'),
  ('rl_04', 'v0.1', 'relationships', 14, 'likert', 'Sinto-me seguro quando sei que faço parte de um grupo.', '[]'::jsonb, true, 'person', 'orphan'),
  ('rl_05', 'v0.1', 'relationships', 15, 'likert', 'Tenho facilidade para expressar o que sinto pelas pessoas.', '[]'::jsonb, true, 'person', 'lover'),
  ('rl_06', 'v0.1', 'relationships', 16, 'likert', 'Respeito os limites dos outros e defendo os meus quando necessário.', '[]'::jsonb, true, 'person', 'warrior'),
  ('rl_07', 'v0.1', 'relationships', 17, 'likert', 'Quando alguém depende de mim, sinto responsabilidade genuína em ajudar.', '[]'::jsonb, true, 'person', 'caregiver'),
  ('rl_08', 'v0.1', 'relationships', 18, 'likert', 'Prefiro poucas relações profundas a muitas relações superficiais.', '[]'::jsonb, true, 'person', 'explorer'),
  ('rl_09', 'v0.1', 'relationships', 19, 'likert', 'Diante de um conflito, procuro compreender o outro lado antes de reagir.', '[]'::jsonb, true, 'person', 'sage'),
  ('ld_01', 'v0.1', 'leadership', 20, 'likert', 'Quando uma decisão precisa ser tomada, assumo a responsabilidade com naturalidade.', '[]'::jsonb, true, 'person', 'ruler'),
  ('ld_02', 'v0.1', 'leadership', 21, 'likert', 'Costumo tomar iniciativa mesmo sem esperar que alguém me autorize.', '[]'::jsonb, true, 'person', 'warrior'),
  ('ld_03', 'v0.1', 'leadership', 22, 'likert', 'Sou disciplinado para cumprir aquilo que me proponho.', '[]'::jsonb, true, 'person', 'warrior'),
  ('ld_04', 'v0.1', 'leadership', 23, 'likert', 'Tenho facilidade para inspirar e mobilizar outras pessoas.', '[]'::jsonb, true, 'person', 'ruler'),
  ('ld_05', 'v0.1', 'leadership', 24, 'likert', 'Prefiro conduzir processos a apenas acompanhar o que acontece.', '[]'::jsonb, true, 'person', 'ruler'),
  ('ld_06', 'v0.1', 'leadership', 25, 'likert', 'Mantenho o foco em meus objetivos mesmo diante de obstáculos.', '[]'::jsonb, true, 'person', 'warrior'),
  ('ld_07', 'v0.1', 'leadership', 26, 'likert', 'Confio na minha capacidade de decidir por conta própria.', '[]'::jsonb, true, 'person', 'explorer'),
  ('ld_08', 'v0.1', 'leadership', 27, 'likert', 'Assumir autoridade me faz sentir confortável e natural.', '[]'::jsonb, true, 'person', 'ruler'),
  ('ld_09', 'v0.1', 'leadership', 28, 'likert', 'Quando lidero, busco extrair o melhor de cada pessoa da equipe.', '[]'::jsonb, true, 'person', 'sage'),
  ('pp_01', 'v0.1', 'purpose', 29, 'likert', 'Tenho um sentido claro que orienta as decisões importantes da minha vida.', '[]'::jsonb, true, 'person', 'magician'),
  ('pp_02', 'v0.1', 'purpose', 30, 'likert', 'Sinto que nasci para contribuir de uma forma específica com as pessoas.', '[]'::jsonb, true, 'person', 'magician'),
  ('pp_03', 'v0.1', 'purpose', 31, 'likert', 'Sonho em deixar uma marca que permaneça depois de mim.', '[]'::jsonb, true, 'person', 'creator'),
  ('pp_04', 'v0.1', 'purpose', 32, 'likert', 'Minhas ações do dia a dia estão alinhadas com aquilo que considero importante.', '[]'::jsonb, true, 'person', 'sage'),
  ('pp_05', 'v0.1', 'purpose', 33, 'likert', 'Tenho uma visão clara do futuro que quero construir para mim.', '[]'::jsonb, true, 'person', 'explorer'),
  ('pp_06', 'v0.1', 'purpose', 34, 'likert', 'O que mais me motiva é gerar impacto real na vida das pessoas.', '[]'::jsonb, true, 'person', 'caregiver'),
  ('pp_07', 'v0.1', 'purpose', 35, 'likert', 'Mesmo diante de dificuldades, encontro sentido naquilo que faço.', '[]'::jsonb, true, 'person', 'warrior'),
  ('cr_01', 'v0.1', 'career', 36, 'likert', 'Prefiro ambientes de trabalho que me permitam autonomia e flexibilidade.', '[]'::jsonb, true, 'person', 'explorer'),
  ('cr_02', 'v0.1', 'career', 37, 'likert', 'Tenho talento natural para organizar processos, prazos e rotinas.', '[]'::jsonb, true, 'person', 'ruler'),
  ('cr_03', 'v0.1', 'career', 38, 'likert', 'Costumo me destacar em atividades que exigem criatividade.', '[]'::jsonb, true, 'person', 'creator'),
  ('cr_04', 'v0.1', 'career', 39, 'likert', 'Quando surge um problema, busco soluções práticas e objetivas.', '[]'::jsonb, true, 'person', 'warrior'),
  ('cr_05', 'v0.1', 'career', 40, 'likert', 'Gosto de variar as atividades e evitar rotinas repetitivas.', '[]'::jsonb, true, 'person', 'explorer'),
  ('cr_06', 'v0.1', 'career', 41, 'likert', 'Tenho facilidade para transformar ideias em ações concretas.', '[]'::jsonb, true, 'person', 'warrior'),
  ('cr_07', 'v0.1', 'career', 42, 'likert', 'Sinto-me realizado quando construo algo do zero.', '[]'::jsonb, true, 'person', 'creator'),
  ('cr_08', 'v0.1', 'career', 43, 'likert', 'Consigo manter o foco em tarefas longas e complexas.', '[]'::jsonb, true, 'person', 'ruler'),
  ('cm_01', 'v0.1', 'communication', 44, 'likert', 'Consigo expressar minhas ideias com clareza.', '[]'::jsonb, true, 'person', 'sage'),
  ('cm_02', 'v0.1', 'communication', 45, 'likert', 'Sou persuasivo quando preciso defender um ponto de vista.', '[]'::jsonb, true, 'person', 'warrior'),
  ('cm_03', 'v0.1', 'communication', 46, 'likert', 'Tenho facilidade para falar diante de grupos de pessoas.', '[]'::jsonb, true, 'person', 'ruler'),
  ('cm_04', 'v0.1', 'communication', 47, 'likert', 'Quando converso, presto atenção real no que o outro está dizendo.', '[]'::jsonb, true, 'person', 'caregiver'),
  ('cm_05', 'v0.1', 'communication', 48, 'likert', 'Costumo ser direto e transparente em minha comunicação.', '[]'::jsonb, true, 'person', 'warrior'),
  ('cm_06', 'v0.1', 'communication', 49, 'likert', 'Uso o bom humor para tornar as conversas mais leves.', '[]'::jsonb, true, 'person', 'jester'),
  ('dc_01', 'v0.1', 'challenges', 50, 'likert', 'Em situações de pressão, mantenho clareza para decidir.', '[]'::jsonb, true, 'person', 'warrior'),
  ('dc_02', 'v0.1', 'challenges', 51, 'likert', 'Quando algo muda de repente, adapto-me com rapidez.', '[]'::jsonb, true, 'person', 'explorer'),
  ('dc_03', 'v0.1', 'challenges', 52, 'likert', 'Quando algo não sai como planejei, é difícil para mim manter a calma.', '[]'::jsonb, true, 'person', 'shadow'),
  ('dc_04', 'v0.1', 'challenges', 53, 'likert', 'Diante de um fracasso, consigo recomeçar sem desanimar.', '[]'::jsonb, true, 'person', 'warrior'),
  ('dc_05', 'v0.1', 'challenges', 54, 'likert', 'Costumo evitar situações em que posso parecer incapaz.', '[]'::jsonb, true, 'person', 'shadow'),
  ('dc_06', 'v0.1', 'challenges', 55, 'likert', 'Preciso da aprovação dos outros para me sentir seguro nas minhas escolhas.', '[]'::jsonb, true, 'person', 'shadow'),
  ('dc_07', 'v0.1', 'challenges', 56, 'likert', 'Quando estou sobrecarregado, insisto em resolver sozinho em vez de pedir ajuda.', '[]'::jsonb, true, 'person', 'shadow'),
  ('dc_08', 'v0.1', 'challenges', 57, 'likert', 'Comparo-me com outras pessoas com mais frequência do que gostaria.', '[]'::jsonb, true, 'person', 'shadow'),
  ('dc_09', 'v0.1', 'challenges', 58, 'likert', 'Quando recebo críticas, costumo levá-las para o lado pessoal.', '[]'::jsonb, true, 'person', 'shadow'),
  ('pt_01', 'v0.1', 'potential', 59, 'likert', 'Sinto que tenho capacidades que ainda não uso plenamente.', '[]'::jsonb, true, 'person', 'magician'),
  ('pt_02', 'v0.1', 'potential', 60, 'likert', 'Aprendo coisas novas com facilidade e rapidez.', '[]'::jsonb, true, 'person', 'explorer'),
  ('pt_03', 'v0.1', 'potential', 61, 'likert', 'Quando quero, consigo mobilizar pessoas em torno de uma causa.', '[]'::jsonb, true, 'person', 'ruler'),
  ('pt_04', 'v0.1', 'potential', 62, 'likert', 'Costumo enxergar soluções que outras pessoas não percebem.', '[]'::jsonb, true, 'person', 'magician'),
  ('pt_05', 'v0.1', 'potential', 63, 'likert', 'Minha intuição costuma me orientar bem nas escolhas.', '[]'::jsonb, true, 'person', 'magician'),
  ('pt_06', 'v0.1', 'potential', 64, 'likert', 'Consigo transformar dificuldades em oportunidades.', '[]'::jsonb, true, 'person', 'creator'),
  ('pt_07', 'v0.1', 'potential', 65, 'likert', 'Sou capaz de improvisar quando não tenho todas as respostas.', '[]'::jsonb, true, 'person', 'jester'),
  ('dv_01', 'v0.1', 'development', 66, 'likert', 'Reconheço minhas contradições internas e entendo que elas fazem parte de quem sou.', '[]'::jsonb, true, 'person', 'sage'),
  ('dv_02', 'v0.1', 'development', 67, 'likert', 'Procuro compreender por que reajo de determinadas formas.', '[]'::jsonb, true, 'person', 'sage'),
  ('dv_03', 'v0.1', 'development', 68, 'likert', 'Assumo responsabilidade pelas escolhas que fiz até aqui.', '[]'::jsonb, true, 'person', 'warrior'),
  ('dv_04', 'v0.1', 'development', 69, 'likert', 'Tenho consciência dos meus padrões de comportamento e de suas repetições.', '[]'::jsonb, true, 'person', 'sage'),
  ('dv_05', 'v0.1', 'development', 70, 'likert', 'Estou aberto a transformar aspectos de mim que já não me servem.', '[]'::jsonb, true, 'person', 'magician'),
  ('dv_06', 'v0.1', 'development', 71, 'likert', 'Consigo integrar minhas dimensões pessoal e profissional em uma vida coerente.', '[]'::jsonb, true, 'person', 'ruler'),
  ('dv_07', 'v0.1', 'development', 72, 'likert', 'Meu comportamento em público reflete bem quem eu sou por dentro.', '[]'::jsonb, true, 'person', 'innocent'),
  ('dv_08', 'v0.1', 'development', 73, 'likert', 'Sinto que estou vivendo um momento importante de transformação.', '[]'::jsonb, true, 'person', 'magician'),
  ('op_01', 'v0.1', 'open', 74, 'open', 'Quais são seus maiores sonhos e aspirações?', '[]'::jsonb, true, 'person', null),
  ('op_02', 'v0.1', 'open', 75, 'open', 'O que motiva você a levantar todos os dias?', '[]'::jsonb, true, 'person', null),
  ('op_03', 'v0.1', 'open', 76, 'open', 'Qual é o principal objetivo que deseja alcançar nesta fase da sua vida?', '[]'::jsonb, true, 'person', null),
  ('op_04', 'v0.1', 'open', 77, 'open', 'Como gostaria de ser lembrado?', '[]'::jsonb, true, 'person', null),
  ('op_05', 'v0.1', 'open', 78, 'open', 'O que você acredita que faz melhor do que a maioria das pessoas?', '[]'::jsonb, true, 'person', null),
  ('op_06', 'v0.1', 'open', 79, 'open', 'O que gostaria de desenvolver em si?', '[]'::jsonb, true, 'person', null),
  ('op_07', 'v0.1', 'open', 80, 'open', 'Qual é hoje o maior desafio que enfrenta?', '[]'::jsonb, true, 'person', null),
  ('op_08', 'v0.1', 'open', 81, 'open', 'Que tipo de contribuição gostaria de oferecer às pessoas?', '[]'::jsonb, true, 'person', null),
  ('op_09', 'v0.1', 'open', 82, 'open', 'Descreva, em poucas palavras, o momento de vida que você vive hoje.', '[]'::jsonb, true, 'person', null),
  ('br_01', 'v0.1', 'brand', 83, 'single', 'A afirmação que mais se aproxima da essência desta marca ou projeto é:', '[{"id":"b1","label":"Oferece segurança e acolhimento, como um abrigo."},{"id":"b2","label":"Questiona padrões e propõe novos caminhos."},{"id":"b3","label":"Oferece conhecimento, clareza e profundidade."},{"id":"b4","label":"Convida à liberdade, à descoberta e à aventura."},{"id":"b5","label":"Cria, inova e transforma ideias em realidades."},{"id":"b6","label":"Lidera, organiza e inspira confiança."},{"id":"b7","label":"Transmite simplicidade, pureza e esperança."},{"id":"b8","label":"Conecta pessoas e gera afeto."},{"id":"b9","label":"Transforma vidas e desperta visão."},{"id":"b10","label":"É forte, determinada e disciplinada."},{"id":"b11","label":"Acolhe a realidade como ela é, com verdade."},{"id":"b12","label":"Traz leveza, humor e espontaneidade."}]'::jsonb, true, 'brand', 'essence'),
  ('br_02', 'v0.1', 'brand', 84, 'multiple', 'O que você deseja que as pessoas percebam imediatamente nesta marca ou projeto?', '[{"id":"p1","label":"Credibilidade"},{"id":"p2","label":"Acolhimento"},{"id":"p3","label":"Inovação"},{"id":"p4","label":"Qualidade"},{"id":"p5","label":"Leveza"},{"id":"p6","label":"Força"},{"id":"p7","label":"Propósito"},{"id":"p8","label":"Conexão"}]'::jsonb, true, 'brand', 'positioning'),
  ('br_03', 'v0.1', 'brand', 85, 'multiple', 'Esta marca busca oferecer principalmente:', '[{"id":"o1","label":"Segurança"},{"id":"o2","label":"Transformação"},{"id":"o3","label":"Conhecimento"},{"id":"o4","label":"Experiências"},{"id":"o5","label":"Soluções criativas"},{"id":"o6","label":"Organização"},{"id":"o7","label":"Esperança"},{"id":"o8","label":"Cuidado"},{"id":"o9","label":"Visão"},{"id":"o10","label":"Resultados"},{"id":"o11","label":"Verdade"},{"id":"o12","label":"Leveza"}]'::jsonb, true, 'brand', 'positioning'),
  ('br_04', 'v0.1', 'brand', 86, 'multiple', 'Esta marca ajuda as pessoas a:', '[{"id":"a1","label":"Sentirem-se protegidas"},{"id":"a2","label":"Rompem padrões"},{"id":"a3","label":"Compreenderem melhor o mundo"},{"id":"a4","label":"Descobrirem novos caminhos"},{"id":"a5","label":"Criarem e realizarem"},{"id":"a6","label":"Liderarem com confiança"},{"id":"a7","label":"Confiar novamente"},{"id":"a8","label":"Conectarem-se com mais profundidade"},{"id":"a9","label":"Transformarem suas vidas"},{"id":"a10","label":"Superarem desafios"},{"id":"a11","label":"Serem mais verdadeiras"},{"id":"a12","label":"Viverem com mais leveza"}]'::jsonb, true, 'brand', 'positioning'),
  ('br_05', 'v0.1', 'brand', 87, 'multiple', 'Como você gostaria que as pessoas descrevessem esta marca?', '[{"id":"d1","label":"Confiável"},{"id":"d2","label":"Humana"},{"id":"d3","label":"Inovadora"},{"id":"d4","label":"Sofisticada"},{"id":"d5","label":"Acolhedora"},{"id":"d6","label":"Determinada"},{"id":"d7","label":"Inspiradora"},{"id":"d8","label":"Autêntica"}]'::jsonb, true, 'brand', 'perception'),
  ('br_06', 'v0.1', 'brand', 88, 'multiple', 'O propósito desta marca está principalmente relacionado a:', '[{"id":"r1","label":"Proteger e cuidar"},{"id":"r2","label":"Provocar mudanças"},{"id":"r3","label":"Compartilhar conhecimento"},{"id":"r4","label":"Expandir horizontes"},{"id":"r5","label":"Criar o novo"},{"id":"r6","label":"Conduzir e organizar"},{"id":"r7","label":"Transmitir esperança"},{"id":"r8","label":"Gerar conexões"},{"id":"r9","label":"Transformar vidas"},{"id":"r10","label":"Gerar impacto"},{"id":"r11","label":"Ser verdadeira"},{"id":"r12","label":"Levar alegria"}]'::jsonb, true, 'brand', 'purpose'),
  ('br_07', 'v0.1', 'brand', 89, 'multiple', 'Quais características você gostaria que estivessem presentes na percepção desta marca?', '[{"id":"c1","label":"Criatividade"},{"id":"c2","label":"Confiança"},{"id":"c3","label":"Organização"},{"id":"c4","label":"Liberdade"},{"id":"c5","label":"Autoridade"},{"id":"c6","label":"Cuidado"},{"id":"c7","label":"Inovação"},{"id":"c8","label":"Simplicidade"},{"id":"c9","label":"Fortalecimento"},{"id":"c10","label":"Propósito"}]'::jsonb, true, 'brand', 'perception'),
  ('br_08', 'v0.1', 'brand', 90, 'text', 'Qual é a principal promessa que esta marca faz?', '[]'::jsonb, true, 'brand', 'essence'),
  ('br_09', 'v0.1', 'brand', 91, 'text', 'Como esta marca se diferencia das demais?', '[]'::jsonb, true, 'brand', 'positioning')
on conflict (qid, version) do update set
  text = excluded.text, options = excluded.options, ord = excluded.ord;

-- Configurações padrão
insert into public.settings (key, value) values
  ('analyst_name', 'Letícia Maria'),
  ('analyst_title', 'Criadora da metodologia SynaptEssence360®'),
  ('analyst_photo', ''),
  ('analyst_bio', 'Especialista responsável pela condução da análise e devolutiva. Toda transformação começa quando novas conexões são criadas.'),
  ('hero_message', 'Toda transformação começa quando novas conexões são criadas.'),
  ('closing_message', 'Toda transformação começa quando novas conexões são criadas.'),
  ('institutional_text', 'A SynaptEssence360® foi concebida para organizar diferentes dimensões da experiência humana em uma leitura estratégica de desenvolvimento.'),
  ('privacy_email', 'contato@synaptessence.com.br')
on conflict (key) do update set value = excluded.value;
